### ISSUE TITLE
Make a Venn diagram from output

### ISSUE THREAD

**Issue by Karimi-81** [ridgelab/JustOrthologs#13]
Hi there,
Thank you for developing JustOrthologs. I have used "run_multiple_species.sh" to create pairwise comparisons and group file for six species. I wonder if you could provide any instruction to present the results using a Venn diagram. There is no information on the total number of CDs or overlaps between more than two species. I would be appreciated if you could help me in this regard.
Thanks

**Comment by miller34** [comment]
Hello!
Thank you for your interest in JustOrthologs. We do not currently provide support for custom queries on the results of run_multiple_species.sh. However, run_multiple_species.sh should create a file that lists genes that were identified as orthologs between all species, so you should be able to count the number of orthologs with genes reported from more than two  species in that output file.
