### ISSUE TITLE
failed to run justortholog

### ISSUE THREAD

**Issue by rocpengliu** [ridgelab/JustOrthologs#14]
Hi there

I have git clone the repository of justortholog.
and I have tried the example using this command
python justOrthologs.py -q smallTest/orthologTest/bonobo.fa -s smallTest/orthologTest/human.fa -o output -c -t 16

but get an error like this:
  File "justOrthologs.py", line 157
    print args.subject, "is not a correct file path!"
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(args.subject, "is not a correct file path!")?

I have installed all the libs
1. sys
2. os
3. multiprocessing
4. argparse

still get the same error

Any idea about this?

Thank you so much!

**Comment by miller34** [comment]
Hello!

Thank you for your interest in JustOrthologs. The issue is with the version of Python. Make sure you're using python 2.7 (or equivalent). It does not currently run on python 3. Cheers!

**Comment by rocpengliu** [comment]
It works!
Thank you so much!
