### ISSUE TITLE
visualization of results

### ISSUE THREAD

**Issue by mictadlo** [ridgelab/JustOrthologs#2]
Hello,
By any chance, do you have any scripts to visualise JustOrthologs' results?

Thank you in advance,

Michal

**Comment by ridgelab** [comment]
Hey Michal,

Thank you for your interest in JustOrthologs. Unfortunately, that functionality is not yet part of the JustOrthologs package. We are actively developing additional tools and modifications for JustOrthologs, so we will add that to the list of requested features.

Best,
Justin
